apiVersion: constraints.gatekeeper.sh/v1alpha1
kind: GCPCMEKRotationConstraintV1
metadata:
  name: cmek_rotation_one_hundred_days
  annotations:
    bundles.validator.forsetisecurity.org/forseti-security: v2.26.0
    description: Checks that CMEK rotation policy is in place and is sufficiently
      short.
spec:
  severity: high
  match:
    target: # {"$ref":"#/definitions/io.k8s.cli.setters.target"}
    - organizations/**
  parameters:
    # Optionaly specify the required key rotation period.  Default is 365 days
    # Valid time units are  "ns", "us", "ms", "s", "m", "h"
    # This is 100 days
    period: 2400h
